.name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      # Optional: Install npm packages if needed for JS libraries
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: |
          cd BlazorAIChat/wwwroot/Lib || exit 0
          npm install dompurify marked || true
        continue-on-error: true
      # Optional: Run EF Core migrations if needed
      - name: Run EF Core migrations
        run: |
          dotnet tool restore
          dotnet ef database update --project BlazorAIChat/BlazorAIChat.csproj || true
        continue-on-error: true
